/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../index';
import * as i2 from './src/image-zoom-container.component.ngfactory';
import * as i3 from './src/image-zoom-lens.component.ngfactory';
import * as i4 from '@angular/common';
export const ImageZoomModuleNgFactory:i0.NgModuleFactory<i1.ImageZoomModule> = i0.ɵcmf(i1.ImageZoomModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ImageZoomContainerNgFactory,i3.ImageZoomLensNgFactory]],[3,i0.ComponentFactoryResolver],
              i0.NgModuleRef]),i0.ɵmpd(4608,i4.NgLocalization,i4.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(512,i4.CommonModule,i4.CommonModule,([] as any[])),
          i0.ɵmpd(512,i1.ImageZoomModule,i1.ImageZoomModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL25hcm90dGFtZGF0dGF0cmV5L0RvY3VtZW50cy9PcGVuIHNvdXJjZS9hbmd1bGFyLWltYWdlLXpvb20vaW5kZXgubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbmFyb3R0YW1kYXR0YXRyZXkvRG9jdW1lbnRzL09wZW4gc291cmNlL2FuZ3VsYXItaW1hZ2Utem9vbS9pbmRleC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
